Add module files to compile on AWS
NOAA-EMC/GDASApp pull request #1082
Opened 2024-04-29 20:43 UTC by weihuang-jedi

Add module files to compile on AWS

Solve issue: #1081 

https://github.com/NOAA-EMC/GDASApp/issues/1081

- Tested on AWS
- Tested on Hera

2024-04-29 21:30 UTC, aerorahul requested changes
Just a minor comment.

2024-04-29 21:30 UTC, aerorahul commented on ush/module-setup.sh
> +    # We are on NCCS discover
```suggestion
    # We are on NOAA Cloud
```

2024-04-29 22:07 UTC, weihuang-jedi commented on ush/module-setup.sh
> +    # We are on NCCS discover
Changed.

2024-04-29 22:09 UTC, aerorahul approved these changes
looks good

2024-04-29 22:47 UTC, weihuang-jedi commented
Thank you @Rahul Mahajan - NOAA Federal ***@***.***> .

On Mon, Apr 29, 2024 at 4:10 PM Rahul Mahajan ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> looks good
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GDASApp/pull/1082#pullrequestreview-2029740909>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASMCH674NDCWVA5GO3ZA3KDY73AMLAVCNFSM6AAAAABG7AU3ESVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMRZG42DAOJQHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-30 12:30 UTC, CoryMartin-NOAA approved these changes

2024-04-30 12:30 UTC, merged

2024-04-30 13:32 UTC, weihuang-jedi commented
Thank you, Cory!

On Tue, Apr 30, 2024 at 6:31 AM Cory Martin ***@***.***>
wrote:

> Merged #1082 <https://github.com/NOAA-EMC/GDASApp/pull/1082> into develop.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/GDASApp/pull/1082#event-12657283214>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASMCH66AXMFZ6EJZZWAZM33Y76FJNAVCNFSM6AAAAABG7AU3ESVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGY2TOMRYGMZDCNA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>