Feature/rtofs in situ
NOAA-EMC/GDASApp pull request #1138
Opened 2024-05-31 21:41 UTC by givelberg

Created 2 converters with corresponding tests, for temperature and salinity.
2 different files are created.
For temperature the file includes
tmp, tmp_err, lon, lat, depth
and metadata sal_typ and flg
Similarly, for salinity..

2024-06-01 13:39 UTC, guillaumevernieres commented on utils/test/CMakeLists.txt
> +# add binary files for the test
Lets stage the files on Hera and Orion so we can switch that test on

2024-06-01 13:40 UTC, guillaumevernieres commented on utils/test/testinput/gdas_rtofsinsitu.yaml
> +input files:
we need to be able to read multiple files

2024-06-01 13:41 UTC, guillaumevernieres commented on utils/test/testinput/gdas_rtofsinsitu.yaml
> +# test:
test reference needs to be used

2024-06-01 13:44 UTC, guillaumevernieres reviewed
Thanks for doing this @givelberg . A few minor comments related to the ctest. We'll figure out where to keep these RTOFS binaries next week.

2024-06-10 11:56 UTC, guillaumevernieres commented
Looks like you forgot to add the yaml files for the tests @givelberg :
```
 6/48 Test #1493: test_gdasapp_util_rtofstmp ............................Subprocess aborted***Exception:   0.82 sec                                                                                                        
Exception: Cannot open ../testinput/gdas_rtofstmp.yaml  (No such file or directory)                                                                                                                                        
terminate called after throwing an instance of 'eckit::CantOpenFile'                                                                                                                                                       
  what():  Cannot open ../testinput/gdas_rtofstmp.yaml  (No such file or directory)                                                                                                                                        
                                                                                                                                                                                                                           
      Start 1494: test_gdasapp_util_rtofssal                                                                                                                                                                               
 7/48 Test #1494: test_gdasapp_util_rtofssal ............................Subprocess aborted***Exception:   0.60 sec                                                                                                        
Exception: Cannot open ../testinput/gdas_rtofssal.yaml  (No such file or directory)                                                                                                                                        
terminate called after throwing an instance of 'eckit::CantOpenFile'                                                                                                                                                       
  what():  Cannot open ../testinput/gdas_rtofssal.yaml  (No such file or directory)             
```

2024-06-10 16:03 UTC, guillaumevernieres requested changes
See comment. I didn't see any other ```HEAD``` or residuals from your last merge, but you might want to double check.
Also, you need to merge develop into your branch again.

2024-06-10 16:03 UTC, guillaumevernieres commented on utils/test/CMakeLists.txt
> +<<<<<<< HEAD
Ha! I'm a terrible reviewer!!!
The build failed because of this @givelberg

2024-06-10 18:41 UTC, guillaumevernieres approved these changes
Thanks @givelberg !

2024-06-10 18:41 UTC, merged

2024-06-11 19:18 UTC, RussTreadon-NOAA commented
This PR changed the hash for the following repos in `sorc/`:  `fv3`, `gsibec`, `gsw`, `land-imsproc`, `land-jediincr`.   The modified hashes in this PR are newer than what was previously in GDASApp `sorc/` except for `gsibec`.

This PR changed gsibec to `[gsibec @ e6e1944](https://github.com/GEOS-ESM/GSIbec/tree/e6e1944e1cb8f339b4eb79acffb5470bb7723b42).  This commit is dated June 26, 2203.

Before this PR was merged into `develop`, we were using [gsibec @ c8ac58d](https://github.com/GEOS-ESM/GSIbec/tree/c8ac58d9b43eb8f890e565d12c88f1b0579c9ccd).  This commit is dated March 8, 2024.  This gsibec hash is [tags/1.2.1](https://github.com/GEOS-ESM/GSIbec/releases/tag/1.2.1).

g-w C96C48_ufs_hybatmDA CI using the current head of GDASApp ([7f4c2fc](https://github.com/NOAA-EMC/GDASApp/commit/7f4c2fc15bcf6c4bdc212b3d64f107fd92fda2ad)) failed when running the gfs and gdas atmanlvar.  Both job aborted with the error message
```
 0: Exception: gsi static covariance does not exist in saber::SaberCentralBlockFactory
 0: Exception: oops::Variational<FV3JEDI, UFO and IODA observations> terminating...
 0: Exception: level: 0
 0: gsi static covariance does not exist in saber::SaberCentralBlockFactory
 0: OOPS Ending   2024-06-11 16:39:22 (UTC+0000)
```
This reason for this failure is that the `gsibec` hash GDASApp currently points at is out of date with other repository snapshots in `sorc/`.  As a test `gsibec` was updated to gsibec `tags/1.2.1` and GDASApp rebuilt.  Reruns of the g-w CI gfs and gdas atmanlvar jobs were successful.

**We need to revert `sorc/gsibec` back to gsibec [`tags/1.2.1`](https://github.com/GEOS-ESM/GSIbec/releases/tag/1.2.1) (hash [c8ac58d](https://github.com/GEOS-ESM/GSIbec/commit/c8ac58d9b43eb8f890e565d12c88f1b0579c9ccd))**

2024-06-11 21:01 UTC, guillaumevernieres commented
Ouch, sorry about this @RussTreadon-NOAA . Not quite sure how I missed this but I did ...