Add and test snow DA increment application code
NOAA-EMC/GDASApp pull request #233
Opened 2022-12-05 23:16 UTC by jiaruidong2017

Add and test snow DA increment application code to GDASApp, and add a ctest verifying this test works as intended (Issue #200). 

Since there is a bug in the PSL `land-apply_jedi_incr` repo, I used my branch for the test for now. I created the PR for the bugfix, and wait them to merge it. Once the PR is merged, I will switch to use the PSL repo. 

Two datasets are required and listed below:
1) JEDI increment data: 
`/scratch2/NCEPDEV/stmp1/Jiarui.Dong/workdir/jedi/20210323.180000.xainc.sfc_data.tile*.nc`
2) Orography data: 
`/scratch1/NCEPDEV/global/glopara/fix/orog/20220805/C48/C48_oro_data.tile*.nc`

2022-12-07 12:40 UTC, jiaruidong2017 commented
@CoryMartin-NOAA Would you please copy the following data into `GDASAPP_TESTDATA`, so that I will modify the script to read these data from `GDASAPP_TESTDATA`? Thanks.

Two datasets are required and listed below: 

JEDI increment data:
`/scratch2/NCEPDEV/stmp1/Jiarui.Dong/workdir/jedi/20210323.180000.xainc.sfc_data.tile*.nc`
Orography data:
`/scratch1/NCEPDEV/global/glopara/fix/orog/20220805/C48/C48_oro_data.tile*.nc`

2022-12-07 14:07 UTC, CoryMartin-NOAA commented
@jiaruidong2017 see `$GDASAPP_TESTDATA/land/C48`. Please note that eventually we will be grabbing things like the orography data from the standard GFS/global fix directories, but that won't be until the land DA support is added to the global workflow.

2022-12-07 14:49 UTC, jiaruidong2017 commented
Thanks @CoryMartin-NOAA for your efforts and comments. I will modify the script to grab data from $GDASAPP_TESTDATA temporally for the ctest.

2022-12-07 16:30 UTC, CoryMartin-NOAA requested changes

2022-12-07 16:30 UTC, CoryMartin-NOAA commented on test/land/apply_jedi_incr.sh
> +module load GDAS/hera
no module purge/load in the test file, the test environment should already be setup properly

2022-12-07 16:30 UTC, CoryMartin-NOAA commented on test/land/apply_jedi_incr.sh
> +mkdir -p $WORKDIR
This should have an extra subdirectory under it so that the test is clean (and it should be `rm -rf` before `mkdir -p` to clean it out.

2022-12-07 16:30 UTC, CoryMartin-NOAA commented on test/land/apply_jedi_incr.sh
> +    exit 10
as Rahul said before, exit with the return code not a 'made up' one.

2022-12-07 16:31 UTC, jiaruidong2017 commented on test/land/apply_jedi_incr.sh
> +    exit 10
@CoryMartin-NOAA I see, and I will change it. Thanks.

2022-12-07 17:34 UTC, jiaruidong2017 commented on test/land/apply_jedi_incr.sh
> +module load GDAS/hera
Removed the module load

2022-12-07 17:35 UTC, jiaruidong2017 commented on test/land/apply_jedi_incr.sh
> +mkdir -p $WORKDIR
Added the `rm -rf $WORKDIR` before `mkdir -p $WORKDIR`.

2022-12-07 17:36 UTC, jiaruidong2017 commented on test/land/apply_jedi_incr.sh
> +    exit 10
Removed this 'made up' exit code.

2022-12-07 17:39 UTC, CoryMartin-NOAA commented on test/land/apply_jedi_incr.sh
> +WORKDIR=$project_binary_dir/test/land
Probably want a subdirectory and not just 'test/land'

2022-12-07 18:00 UTC, jiaruidong2017 commented on test/land/apply_jedi_incr.sh
> +WORKDIR=$project_binary_dir/test/land
Okay, I will add` testrun` subdirectory and test it. Thanks.

2022-12-07 18:06 UTC, CoryMartin-NOAA commented on test/land/apply_jedi_incr.sh
> +WORKDIR=$project_binary_dir/test/land
I'm thinking more something like `test/land/apply_jedi_incr` so that it is a clean directory for each test.

2022-12-07 18:12 UTC, jiaruidong2017 commented on test/land/apply_jedi_incr.sh
> +WORKDIR=$project_binary_dir/test/land
Great idea! I will change to `test/land/apply_jediincr` for this ctest. Thanks.

2022-12-07 18:34 UTC, jiaruidong2017 commented on test/land/apply_jedi_incr.sh
> +WORKDIR=$project_binary_dir/test/land
Added the subdirectory as suggested.

2022-12-07 18:52 UTC, CoryMartin-NOAA approved these changes, later dismissed
Looks good to me as far as I can tell, will merge once tests pass on Hera and Orion.

2022-12-07 21:19 UTC, jiaruidong2017 commented
@CoryMartin-NOAA I just modified two previous scripts (create_bkg_ens.sh and test_imsproc.sh) and make them to have same working directories at test/land/subdirectory. I will resubmit the ctests. Thanks.

2022-12-08 14:27 UTC, CoryMartin-NOAA approved these changes

2022-12-08 14:27 UTC, CoryMartin-NOAA commented
Looks good thanks @jiaruidong2017

2022-12-08 14:28 UTC, merged