Add GHRSST SST IODA converter
NOAA-EMC/GDASApp pull request #666
Opened 2023-10-06 19:24 UTC by ShastriPaturi

This PR adds the GHRSST SST IODA converter.
The original data are the L3U from the NCEP data tanks

Fixes #609

2023-10-06 19:33 UTC, guillaumevernieres requested changes
fix the code norm and see comments below.

2023-10-06 19:33 UTC, guillaumevernieres commented on utils/obsproc/applications/gdas_obsprovider2ioda.h
> +        oops::Log::info() << "GHRSST!" << std::endl;
look at what's done for the other provider, and remove the log. You clearly have not looked at the output, that code is not writing a ioda file.

2023-10-06 19:33 UTC, guillaumevernieres commented on utils/test/testinput/gdas_ghrsst2ioda.yaml
> +#- ghrsst_sst_mb_202107010100.nc4
you need to test the concatenation as well, uncomment line 8.

2023-10-06 21:26 UTC, apchoiCMD requested changes

2023-10-06 21:26 UTC, apchoiCMD commented on utils/test/testinput/gdas_ghrsst2ioda.yaml
> +variable: seaSurfaceTemperature
Also remove the variables

2023-10-06 21:26 UTC, apchoiCMD commented on utils/obsproc/applications/gdas_obsprovider2ioda.h
> +        Ghrsst2Ioda conv2ioda(fullConfig);
missing `this->getComm()` after `fullConfig`

2023-10-06 21:26 UTC, apchoiCMD commented on utils/test/CMakeLists.txt
> +  testinput/gdas_smos2ioda.yaml
conflict `gdas_smos2ioda.yaml`

2023-10-10 12:29 UTC, guillaumevernieres commented
Closing your PR @ShastriPaturi . I'll submit a PR with your work later today or tomorrow, along with the sub-sampling/superobing tools.

2023-10-10 12:29 UTC, closed without merging