Add the feature of comparing variables to reference files
NOAA-EMC/GDASApp pull request #772
Opened 2023-11-27 21:09 UTC by apchoiCMD

#### Work added
- Mimic to add function for comparing output to test reference files at each converter, currently ```Ghrsst2Ioda.h``` converter only
- Set two inputs at each yaml file and remove unnecessary variable 

#### Work needed if possible
- Think more generic code to put ```iodaVars.testOutput()```
- However, ```util.h``` currently has a proper fuction

2023-11-27 21:18 UTC, guillaumevernieres commented
@apchoiCMD , I thought we decided last week to move the iodavars.testoutput call in NetCDFToIodaConverter.h . That didn't work?

2023-11-27 21:21 UTC, apchoiCMD commented
> @apchoiCMD , I thought we decided last week to move the iodavars.testoutput call in NetCDFToIodaConverter.h . That didn't work?

@guillaumevernieres Yes, we did but it didn't work for me and ```util.h``` has well organized functions so that I decided to use as same as ghrsst2ioda.h , but we will need to discuss it.

2023-11-27 21:33 UTC, guillaumevernieres commented
> > @apchoiCMD , I thought we decided last week to move the iodavars.testoutput call in NetCDFToIodaConverter.h . That didn't work?
> 
> @guillaumevernieres Yes, we did but it didn't work for me and `util.h` has well organized functions so that I decided to use as same as ghrsst2ioda.h , but we will need to discuss it.

I don't know why you feel the need to add a laugh emoji to all my posts @apchoiCMD . I was not trying to be funny with the question above. 
What exactly is it that you tried that did not work? I don't understand what you mean with the 2 bullets under **Work needed if possible**. I don't mind merging as is if there's an issue moving the `testoutput` to the base class, but I'd need to understand what the issue is first.

2023-11-27 21:47 UTC, apchoiCMD commented
> > > @apchoiCMD , I thought we decided last week to move the iodavars.testoutput call in NetCDFToIodaConverter.h . That didn't work?
> > 
> > 
> > @guillaumevernieres Yes, we did but it didn't work for me and `util.h` has well organized functions so that I decided to use as same as ghrsst2ioda.h , but we will need to discuss it.
> 
> I don't know why you feel the need to add a laugh emoji to all my posts @apchoiCMD . I was not trying to be funny with the question above. What exactly is it that you tried that did not work? I don't understand what you mean with the 2 bullets under **Work needed if possible**. I don't mind merging as is if there's an issue moving the `testoutput` to the base class, but I'd need to understand what the issue is first.

@guillaumevernieres here is my thought, `util.h` has now all functions that connected to all converters as well as NetCDFToIodaConverter.h and I thought you separated it because you wanted to make NetCDFToIodaConverter.h as simple as possible. As I saw functions that are append, trim and output in `util.h` together, I don't think it makes a sense that we move `output` only. Correct me if I am wrong and removed **Work needed if possible**

2023-11-27 23:01 UTC, guillaumevernieres requested changes
Looks good @apchoiCMD , my only request is to move the call to iodavars.testoutput to the base class. I just tested it and it works fine.

2023-11-27 23:01 UTC, guillaumevernieres commented on utils/obsproc/IcecAmsr2Ioda.h
> +      // Test output
Move this to the base-class. I just tested it and it works fine, you just need to adjust your reference file.

2023-11-27 23:01 UTC, guillaumevernieres commented on utils/obsproc/Rads2Ioda.h
> +       // Test output
same comment as above

2023-11-29 20:29 UTC, guillaumevernieres approved these changes
Looks good. Thanks @apchoiCMD .

2023-11-29 20:31 UTC, merged